open("C:/Users/mikep/Desktop/project/data/examples/*tif");
makeRectangle(7, 6, 218, 218);
run("Crop");
run("8-bit");
setAutoThreshold("Default dark");
//run("Threshold...");
//setThreshold(145, 229);
setOption("BlackBackground", false);
run("Convert to Mask");
saveAs("Tiff", "C:/Users/mikep/Desktop/1212/download2.tif");